- name: Ad-centos7
  hosts: all
  tasks:
  
    - name: Install adcli sssd authconfig
      yum:
        name: adcli, sssd, authconfig
        state: present
  
  
  
  
    - name: Install epel-release
      yum:
        name: epel-release
        state: present
  
        
    - name: Join system to AD and add the computer object in the Linux OU
      expect:
        command: adcli join --user={{ username }} nscloud.sl.net
        responses:
          Password for *: "{{ password }}"
  
    - name: Copy a new file krb5.conf
      copy:
        src: /files/krb5.conf
        dest: /etc/krb5.conf
        owner: root
        group: root
        mode: 0644
        
        
    - name: Copy a new file sssd.conf
      copy:
        src: /files/sssd.conf
        dest: /etc/sssd.conf
        owner: root
        group: root
        mode: 0644
    
          
    - name: Atualizando e configurando a autenticação
      command: authconfig --enablesssd --enablesssdauth --enablemkhomedir --update
        
   
         
    - name: Add the LinuxAdmins AD Group to sudoers
      lineinfile:
        dest: /etc/sudoers
        line: '%linuxadmins@nscloud.sl.net        ALL=(ALL)       ALL'
        insertafter: '^%wheel'

    - name: restart sssd
      service:
        name: sssd
        state: restarted
    
