- name: Install Zabbix Agent
  hosts: all
  tasks:
    - name: Install Zabbix Agent
      yum_repository:
        name: zabbix
        description: Zabbix Official Repository - $basearch
        baseurl: http://repo.zabbix.com/zabbix/3.4/rhel/7/$basearch/
        gpgcheck: yes
        
    - name: Install Zabbix Agent
      yum_repository:
        name: zabbix-non-supported
        description: Zabbix Official Repository non-supported - $basearch
        baseurl: http://repo.zabbix.com/non-supported/rhel/7/$basearch/
        gpgcheck: yes
        
        
