- name: Install Zabbix Agent
  hosts: all
  tasks:
    - name: Install Zabbix Agent
      yum: name=https://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-agent-3.4.2-1.el7.x86_64.rpm
      when: ansible_os_family == "RedHat"
      
      
    - name: Copy a new file sssd.conf
      copy:
        src: /files/zabbix_agentd.conf
        dest: /home/zabbix_agentd.conf
        owner: root
        group: root
        mode: 0644
      
      
    - replace:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server=127\.0\.0\.1'
        replace: 'Server=10.150.247.61'
      
      
    - replace:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^ServerActive=127\.0\.0\.1'
        replace: 'ServerActive=10.150.247.61'
        
          

      
      
      
      
           
        
        
