- name: Install Zabbix Agent
  hosts: all
  tasks:
    - name: Install Zabbix Agent
      yum: name=https://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-agent-3.4.2-1.el7.x86_64.rpm
      when: ansible_os_family == "RedHat"
      notify: start zabbix
      
      
      
      
    - name: Copy a new file agentzabbix.sh
      copy:
        src: /files/agentzabbix.sh
        dest: /home/agentzabbix.sh
        owner: root
        group: root
        mode: 0774
      
      
    - replace:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server=127\.0\.0\.1'
        replace: 'Server=10.150.247.61'
      
      
    - replace:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^ServerActive=127\.0\.0\.1'
        replace: 'ServerActive=10.150.247.61'
        
        
        
    - name: Insere Hostname
      shell: '/home/./agentzabbix.sh'
      notify: restart zabbix
      
      
      
      handlers:
      - name: restart zabbix
        service: name=zabbix-agent state=restarted
      
      - name: start zabbix
        service: name=zabbix-agent state=started
      
      
        
        
        
        
          

      
      
      
      
           
        
        
