- name: upgrade all packages
  hosts: all
  tasks:
    - name: upgrade all packages
      yum: name=* state=latest
      when: ansible_os_family == "RedHat"
        
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
        when: ansible_os_family == "Debian"
